 username =  //input[@name="username"] 
 password =  //input[@name="password"] 
 signInButton =  //button[@type="submit"] 
 Admin =  //span[text()="Admin"] 
 addButton =  //button[normalize-space()="Add"] 
 userRole =  //label[normalize-space()="User Role"]/following::div[contains(@class,"oxd-select-text")][1] 
 userRoleAdmin =  //div[@role="listbox"]//span[normalize-space()="Admin"] 
 employeeName =  //input[@placeholder="Type for hints..."] 
 employeeNamemandaakhiluser =  //div[@role="listbox"]//span[contains(text(),"manda")] 
 status =  //label[normalize-space()="Status"]/following::div[contains(@class,"oxd-select-text")] 
 statusEnabled =  //div[@role="listbox"]//span[normalize-space()="Enabled"] 
 usernameForNewUser =  //label[normalize-space()="Username"]/following::input[1] 
 passwordForNewUser =  //label[normalize-space()="Password"]/following::input[1] 
 confirmPasswordForNewUser =  //label[normalize-space()="Confirm Password"]/following::input[1] 
 saveButton =  //button[normalize-space()="Save"] 
	